name: Deploy docs only
on: workflow_dispatch
jobs:
  # Deploys documentation to github pages
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 
      - uses: actions/setup-node@v2
      - run: npm i
      - run: npm i @ts-docs/default-docs-structure
      - run: tsc
      - run: git clone https://github.com/ts-docs/ts-extractor.git
      - run: node dist/cli
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          branch: gh-pages
          folder: docs