name: Publish package
on:
  workflow_dispatch:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest 
    permissions: 
      contents: read
      packages: write 
    steps:
      - name: Publish Documentation Structure
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_TOKEN }}
          repository: ts-docs/default-docs-structure
          event-type: publish
      - name: Publish this module
        uses: actions/checkout@v2
        uses: actions/setup-node@v2
        with:
          registry-url: 'https://registry.npmjs.org'
        run: npm i
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}